---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: Enable and start httpd
      service: httpd
      state: started
      enabled: yes

